### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by davalb** [mutecomm/mute#2]
On this step of the installation: ```go get -u -v github.com/mutecomm/mute/cmd/...```
I get the following error message: 
```
# github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher
In file included from src/github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher/aes.c:33:
In file included from src/github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher/tomcrypt.h:67:
src/github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher/tomcrypt_macros.h:269:24: error: constraint 'I' expects an integer constant expression
src/github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher/tomcrypt_macros.h:277:24: error: constraint 'I' expects an integer constant expression
src/github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher/tomcrypt_macros.h:368:24: error: constraint 'J' expects an integer constant expression
src/github.com/mutecomm/mute/vendor/github.com/mutecomm/go-sqlcipher/tomcrypt_macros.h:376:24: error: constraint 'J' expects an integer constant expression
```
Can you help me out with this?

**Comment by frankbraun** [comment]
Could you tell me the OS you are using and the version of your gcc (output of `gcc --version`)?
Thanks for the report!

**Comment by bendiken** [comment]
I got the same error attempting the installation on Mac OS X 10.10.5. Find my installation log at https://gist.github.com/bendiken/983f49e0daedabcac4cf

The error concerns the "I" in inline x86 assembly such as the following from `go-sqlcipher/tomcrypt_macros`, line 269:

    static inline unsigned ROLc(unsigned word, const int i)
    {
       asm ("roll %2,%0"
          :"=r" (word)
          :"0" (word),"I" (i));
       return word;
    }

The error is most likely due to OS X having purged GCC in favor of Clang, and that piece of code not having been tested for or ported to Clang.

To reproduce on another platform, I suspect you need only set `CC=clang`. Now, it's [not immediately clear](https://gist.github.com/yamaya/2924292) which upstream version of Clang the Apple version 700 corresponds to, but it's certainly newer than Clang 3.6.0.

**Comment by davalb** [comment]
I have OS X 10.10.5 as well. The output of `ggc --version` is
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by frankbraun** [comment]
I couldn't reproduce the problem on Mac OS X 10.10.5 with LLVM version 6.1.0, but the problem should be fixed now since I disabled all non-portable assembler code. I will test myself tomorrow after the update to LLVM version 7.0.0. Thanks for the report!

**Comment by davalb** [comment]
Fixed. I had no problem when I tried it again. Thanks!
